const express=require("express")
const app=express()
const {userRoute}=require("./route/user.route")
const {postRoute}=require("./route/post.route")
const {auth}=require("./middleware/auth.middleware")
const cors=require("cors")
app.use(express.json())
app.use(cors())
app.use("/user",userRoute)
app.use(auth)
app.use("/post",postRoute)
app.listen(process.env.port,()=>{
    console.log("server start")
})